_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": gpu_util
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": timestamp
              "6":
                - 3
              "7": []
            - "1": ram_used_MB
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": cpu_util
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gpu_alloc_MB
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": gpu_reserved_MB
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": cpu_proc_MB
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": ram_total_MB
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 7
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": linux-aarch64
activation:
    value: true
autocast_context:
    value: false
batch_size:
    value: 1
check_diff:
    value: false
debug:
    value: false
finetune_type:
    value: lora
hook:
    value: true
layerwise:
    value: false
level:
    value: 1
max_length:
    value: 2048
model:
    value: /opt/models/hf/TinyLlama-1.1B-Chat-v1.0
outdir:
    value: ./weight_comp/prepare_weight/TinyLlama-1.1B-zstd-compressed-weights/level18
print_ratio:
    value: false
print_time:
    value: false
round:
    value: 5
weight:
    value: true
